### ISSUE TITLE
Som bruger vil jeg gerne kunne oprette et projekt

### ISSUE THREAD

**Issue by Celinelundm** [ChristofferLundKEA/CalcMaster2000#5]
**Related issues:**

- [ ] #41 
- [ ] #42 
- [ ] #43 
- [ ] #44  

Acceptkriterier:
- Brugeren kan indtaste projektnavn, beskrivelse, startdato, slutdato, og estimeret tid i formularen Ved klik på "Opret projekt" bliver projektet gemt i databasen.
- Fejlmeddelelser vises hvis felter fx ikke er udfyldt eller forretningslogikken ikke bliver overholdt
- Det oprettede projekt er synligt i projektoversigten, og alle data gemmes korrekt i databasen

**Comment by ChristofferLundKEA** [comment]
#19
